### ISSUE TITLE
Application crashes due to faulting DLL

### ISSUE THREAD

**Issue by StreamUtilitySuite** [visioforge/.Net-SDK-s-samples#10]
When using the Simple Video Capture Demo (.NET 6) and attempting to use it with the Snap Camera app and MP4 (GPU), I can preview the video just fine, but when I switch to Capture, it acts like it's going to work and then the whole application crashes.

When I look in the Event Viewer, this is what it shows:

**Faulting application name:** WinForms Simple Video Capture Demo.exe, version: 15.4.17.0, time stamp: 0x62cf0990
**Faulting module name:** VisioForge_MFT64.DLL, version: 15.3.46.0, time stamp: 0x62d19a4e
**Exception code:** 0xc0000094
**Fault offset:** 0x000000000013f630
**Faulting process id:** 0x3958
**Faulting application start time:** 0x01d8c189727f0c44
**Faulting application path:** C:\Users\tenni\Downloads\Net-SDK-s-samples-master\.Net-SDK-s-samples-master\Video Capture SDK\WinForms\CSharp\Simple VideoCapture\bin\Debug\net6.0-windows\WinForms Simple Video Capture Demo.exe
**Faulting module path:** C:\Users\tenni\Downloads\Net-SDK-s-samples-master\.Net-SDK-s-samples-master\Video Capture SDK\WinForms\CSharp\Simple VideoCapture\bin\Debug\net6.0-windows\VisioForge_MFT64.DLL
**Report Id:** cc61b6f1-fc4f-463c-819c-1df6ff02fad2
**Faulting package full name:** 
**Faulting package-relative application ID:** 

The GPU encoding works fine on the webcam itself but I need it to work using the Snap Camera app source.

CPU also works fine but it uses a lot of resources so I was hoping to offload it to the GPU but right now I'm unable to.

Any ideas on how to get it to work with the GPU?

**Comment by visioforge** [comment]
Snap Camera app provides wrong timestamps, that's a problem. Let us find a workaround for this.

**Comment by visioforge** [comment]
The problem has been resolved in v15.4.18.

**Comment by StreamUtilitySuite** [comment]
Yep! Looks like that fixed it! Thanks for the quick fix!
