### ISSUE TITLE
issue 

### ISSUE THREAD

**Issue by TomaszMyszak** [visioforge/.Net-SDK-s-samples#11]
i'm trying your solusion. I have camera Ganz ZN8. 

I using your code to run capture (https://www.youtube.com/watch?v=qX3AiGyWbO8)

and have answer:

Unable to load filter module, file does not exists: LAVSplitter.ax

Unable to create filter (from file): LAV Splitter Source. Please check Deployment on the product page.

Unable to add filter from file LAV Splitter Source. Trying to add using CLSID.

Unable to set URL to LAV Splitter Source filter

Unable to load filter module, file does not exists: LAVVideo.ax

Unable to create filter (from file): LAV Video Decoder. Please check Deployment on the product page.

Unable to add filter from file LAV Video Decoder. Trying to add using CLSID.

Unable to load filter module, file does not exists: VisioForge_MP4_Muxer_v10_x64.ax

Unable to create filter (from file): VisioForge MP4 Muxer v10. Please check Deployment on the product page.

Unable to add filter from file VisioForge MP4 Muxer v10. Trying to add using CLSID.

Unable to add filter in AddFilterFromClsid. Retrieving the COM class factory for component with CLSID {0B0D654C-7AC1-441E-9C4D-3C29ABEDB6A8} failed due to the following error: 80040154 Class not registered (0x80040154 (REGDB_E_CLASSNOTREG)).

Unable to init VisioForge MP4 muxer.

Unable to connect main video renderer to video output pin

Unable to run filter graph. Error code: 0x8000FFFF

**Comment by visioforge** [comment]
Hi. 

This code - https://github.com/visioforge/.Net-SDK-s-samples/tree/master/Video%20Capture%20SDK/_CodeSnippets/ip-camera-capture-mp4 ?

**Comment by TomaszMyszak** [comment]
yes, today im use your code:
ip-camera-capture-mp4 NuGet net472

answer is:

"Severity	Code	Description	Project	File	Line	Category	Suppression State	Tool
Error	CS0029	Cannot implicitly convert type 'System.Uri' to 'string'	ip-camera-capture-mp4 NuGet net472 (net472)	C:\Users\tmysz\Downloads\Net-SDK-s-samples-master\.Net-SDK-s-samples-master\Video Capture SDK\_CodeSnippets\ip-camera-capture-mp4\Form1.cs	38	Compiler	Active	Compiler

Severity	Code	Description	Project	File	Line	Category	Suppression State	Tool
Error	MSB3821	Couldn't process file Form1.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	ip-camera-capture-mp4 NuGet net472	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	3262			GenerateResource

**Comment by visioforge** [comment]
It's a Visual Studio problem with any downloaded WinForms project. Try to use git to clone the repository.

Or check the following - https://learn.microsoft.com/en-us/answers/questions/123700/form1resx-being-in-the-internet-or-restricted-zone.html
