### ISSUE TITLE
Identify fake and real WebCams

### ISSUE THREAD

**Issue by YasVisibility** [visioforge/.Net-SDK-s-samples#13]
Hello,

I want get real webcams and filter fake ones, For now I am using VideoCaptureCore method Video_CaptureDevices, Is there any way we can filter fake webcams?

Many Thanks,

**Comment by visioforge** [comment]
Hi. No really, because "fake" webcams usually have drivers to make them real and look the same. 
You can filter some cameras by asking for camera control properties that are usually not available by virtual cameras.
Also, you can hardcode a list of popular cameras like ManyCam or Camo.
