### ISSUE TITLE
MultiScreen

### ISSUE THREAD

**Issue by Robjnunn** [visioforge/.Net-SDK-s-samples#18]
Hello

I have been using your Video Capture SDK for many years. I am having a issue with the multi screen option. 

When I tested using your main Demo  when I check the Draw Video on panels I get the following message in the Telemetry "[VideoCaptureCore][CaptureMain] Capture exception: Object reference not set to an instance of an object." and no video preview starts

I can start and stop the Video Preview when not selected with no issue.

Thanks for you Help

**Comment by visioforge** [comment]
Hi

WinForms or WPF?

**Comment by Robjnunn** [comment]
WinForms 
![Screenshot 2024-02-06 142516](https://github.com/visioforge/.Net-SDK-s-samples/assets/159146788/f36df77b-4880-4c6b-8895-305ae4657b80)

**Comment by visioforge** [comment]
Fixed in v15.8.10.
