### ISSUE TITLE
Output file not saving

### ISSUE THREAD

**Issue by muradibrahimli** [visioforge/.Net-SDK-s-samples#2]
when I deploy the app using ClickOnce and installing from setup.exe file, I get the following errors (highlighted). Seems that there is a problem with deployment. Can you explain how deployment should be done?

[DEBUG] Machine.PageMain.videoCap_OnError-1 - This message Unable to create filter: VisioForge MP4 muxer

```
videoCap.Video_CaptureDevice = videoCap.Video_CaptureDevicesInfo[0].Name;
videoCap.Audio_CaptureDevice = videoCap.Audio_CaptureDevicesInfo[0].Name;
 videoCap.Output_Format = new VFMP4v8v10Output();
videoCap.Mode = VisioForge.Types.VFVideoCaptureMode.VideoCapture; 
videoCap.Output_Filename = @"C:\Terminal\test\output.mp4";
 
```

**Comment by ElshadR** [comment]
I have same problem .net 5

**Comment by Haciyev0110** [comment]
Output file not saving to folder. net core 3.1

**Comment by visioforge** [comment]
Please update SDK to the 14.x.
