### ISSUE TITLE
Preview not showing WinUI Demo solution

### ISSUE THREAD

**Issue by karmelcorn** [visioforge/.Net-SDK-s-samples#20]
I was able to compile the VisoForge.VideoCapture.Demos.CS WinUI.sln however the live-preview does not show up. Was anyone able to compile and run the application successfully? I am using dot net 6.

**Comment by visioforge** [comment]
Do you have something in the log?

![2024-02-20_11-05-56](https://github.com/visioforge/.Net-SDK-s-samples/assets/4507925/a5971126-7128-44f7-8960-97188a0f7244)

**Comment by karmelcorn** [comment]
![image](https://github.com/visioforge/.Net-SDK-s-samples/assets/45998347/0ea06c94-cfe9-43e2-b22a-fea15587ea64)
![image](https://github.com/visioforge/.Net-SDK-s-samples/assets/45998347/708b2b50-b60c-4789-835d-794f6b5a8d24)

**Comment by karmelcorn** [comment]
I get the same error log when I run the VisioForge.VideoCapture.Demos.CS(NuGet)net6.sln. But it actually works on the WPF version. Preview and recording works correctly on the WPF version but not the WinUI version.

**Comment by visioforge** [comment]
Please check the updated sample. We have found an issue - the best format was used by default, and the combo box was ignored. The sample code issue, not SDK.

**Comment by karmelcorn** [comment]
Hi, I added the line in         `VideoCapture1.Video_CaptureDevice.Format_UseBest = false;`

But the preview is still not working and the video recording seems to be recorded/playback at 2x the speed...

**Comment by visioforge** [comment]
Please share logs - https://www.visioforge.com/help/docs/dotnet/general/sendlogs/

**Comment by karmelcorn** [comment]
[VisioForge.zip](https://github.com/visioforge/.Net-SDK-s-samples/files/14374882/VisioForge.zip)

**Comment by karmelcorn** [comment]
Hi, were you able to see the logs? Any updates on what might be causing the issue?

**Comment by visioforge** [comment]
I was able to check logs. For some reason the frame rate is 0 in your settings. Could you debug code?

Also you can send me a email to support@visioforge.com, and I will be able to connect in AnyDesk to help or debug.

**Comment by karmelcorn** [comment]
Hi I have sent the email, let me know if you did not receive it. 

Although the recording works fine.. is there a different place that's setting the framerate for preview?

**Comment by visioforge** [comment]
Try to hardcode the VideoCapture1.Video_CaptureDevice.FrameRate property. Or check that it's assigned on the btStart method call. 

Yes, I've replied to your email.
