### ISSUE TITLE
SimpleCapture8 MainPage StartPreview compilation error

### ISSUE THREAD

**Issue by goatrodeosoftware** [visioforge/.Net-SDK-s-samples#22]
Line 301 generates this type conversion error:
            _core.Audio_OutputDevice = (await DeviceEnumerator.Shared.AudioOutputsAsync()).Where(device => device.DisplayName == btSpeakers.Text).First();
Cannot implicitly convert type 'VisioForge.Core.Types.X.Output.AudioOutputDeviceInfo' to 'VisioForge.Core.Types.X.AudioRenderers.IAudioRendererSettings'. An explicit conversion exists (are you missing a cast?)	SimpleCapture8 (net8.0-android), SimpleCapture8 (net8.0-ios), SimpleCapture8 (net8.0-windows10.0.19041.0)	C:\Users\andy_\Downloads\.Net-SDK-s-samples-master\Video Capture SDK X (crossplatform)\MAUI\SimpleCapture\MainPage.xaml.cs	301	
Happy to submit a PR if someone can point me in the right direction

**Comment by visioforge** [comment]
Hi

Please check the updated code.

We've changed an API (and we're not happy to do that); for some reason, after one of the MAUI updates, we missed it in Actions.

**Comment by goatrodeosoftware** [comment]
That did the job- thanks.
