### ISSUE TITLE
Black screen, no streaming on Android, iOS

### ISSUE THREAD

**Issue by goatrodeosoftware** [visioforge/.Net-SDK-s-samples#23]
I can run the sample projects, both viewing and streaming to YouTube, successfully on Windows, but it looks like something is going wrong with the video portion of running on Android (emulator or device) and iOS.  I get past _core.StartAsync at the end of StartPreview and it returns true, but there's no video and YouTube doesn't detect input to start/resume the stream. I do get audio.

[Debug window.txt](https://github.com/visioforge/.Net-SDK-s-samples/files/15279363/Debug.window.txt)
[logcat.txt](https://github.com/visioforge/.Net-SDK-s-samples/files/15279364/logcat.txt)

**Comment by visioforge** [comment]
The problem has been resolved in the latest update.

**Comment by goatrodeosoftware** [comment]
@visioforge  I just ran the sample project on an emulator and device and got this error on launch:
![image](https://github.com/visioforge/.Net-SDK-s-samples/assets/88161688/79baf9c4-885b-4d14-8515-bcde09cb410a)

**Comment by visioforge** [comment]
> @visioforge I just ran the sample project on an emulator

Which sample project?

**Comment by goatrodeosoftware** [comment]
> > @visioforge I just ran the sample project on an emulator
> 
> Which sample project?

Both the media blocks SDK and media capture SDK X for Maui 8

**Comment by visioforge** [comment]
Please check v15.9.61 update.
