### ISSUE TITLE
spinnakerNET_v140.dll could not be loaded

### ISSUE THREAD

**Issue by BergEmilio** [visioforge/.Net-SDK-s-samples#24]
I download the sample code and try to access FLIR USB3 camera, but the dll for FLIR camera can not be loaded on any framework.

Message and stacktrace as below: (I only paste info about .net 7.0, but it's almost the same on other frameworks)

A procedure imported by 'D:\VS2022\Video Capture SDK X (crossplatform)\WPF\CSharp\USB3V-GigE Spinnaker\bin\Debug\net7.0-windows\SpinnakerNET_v140.dll' could not be loaded.

VisioForge.Plugins.Spinnaker.SpinnakerEnumerator.EnumerateAsync.AnonymousMethod__10_0()
    System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, object)
    System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, object)
    System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task, System.Threading.Thread)
    USB3V_GigE_Spinnaker.MainWindow.Window_Loaded(object, System.Windows.RoutedEventArgs) at MainWindow.xaml.cs

I am using VS2022 and try to update to latest version.
Do I miss any thing to run this correctly?

**Comment by visioforge** [comment]
Hi

It's a problem with the Spinnaker assembly that is available only for .Net 4.x. We're working on an update that will use C++ DLL.

**Comment by visioforge** [comment]
The problem was resolved in v15.9.66.
