### ISSUE TITLE
Settings only save when frame rate is set to 15 fps

### ISSUE THREAD

**Issue by richardk1982** [visioforge/.Net-SDK-s-samples#26]
I am testing the Video Capture SDK demo for WPF.  I've tested the Main Demo folder and the Simple Video Capture folder.  When recording an MP4, changing the frame rate to anything other than 15 fps doesn't save the other settings.  For example, this combination of settings doesn't work: 1280x720 YUY2, 16 bit, 59 fps, MP4 format, Rate Control: CBR, Video Bitrate 12000 kbps, Audio Bitrate: 256 kbps.  It will record the video but will not use the values specified.  Is this a glitch that can be fixed?

**Comment by visioforge** [comment]
Hi

Please share a list of supported video formats by your camera. 

YUY2 requires 16 bits per pixel (2 bytes). Resolution (1280x720). 1280×720=921,6001280×720=921,600 pixels per frame. Data rate per frame:  921,600 pixels/frame×2 bytes/pixel=1,843,200 bytes/frame. Theoretical USB 2.0 bandwidth is 320 Mbps = 40 MBps. Now divide the bandwidth by the size of one frame: 40 MBps÷1.8432 MB/frame≈21.7 frames per second.

So, the YUY2 theoretical limit for a USB 2.0 camera is 21 fps. In real life, the Logitech C920 has 15 fps, as I remember.

**Comment by richardk1982** [comment]
Hi.  Thank you for your comment. It clued me in to why the settings wasn't saving.  My capture device was set to 15 fps. Once I changed that setting, everything else worked out.  Apologies for my oversight. Thank you for your help. I am closing the issue.
