### ISSUE TITLE
Question about library

### ISSUE THREAD

**Issue by farhadmammadli** [visioforge/.Net-SDK-s-samples#3]
Hi.
I noticed that you removed the non-trial version of VideoCapture and replaced it with VideoCapture.TRIAL
https://gist.github.com/visioforge/4b529f7f2b8de91574ed6e5d94ae0885/revisions
Is it a sign of deprecation?

- // https://www.nuget.org/packages/VisioForge.DotNet.VideoCapture/
+ // https://www.nuget.org/packages/VisioForge.DotNet.VideoCapture.TRIAL/

**Comment by visioforge** [comment]
Hi

We made it because many tutorials and old clients still use the TRIAL package. Right now it's duplicate packages. We'll stop updating the TRIAL version after one year.
