### ISSUE TITLE
VideoFrameBufferEventArgs.FrameArray is always null when the event is triggered

### ISSUE THREAD

**Issue by fortminors** [visioforge/.Net-SDK-s-samples#5]
Hello!

First of all, that's a great library to use and thank you for sharing it with everyone.

I've downloaded the Simple Video Capture Demo WPF example and just added these lines of code to btStart_Click:

```
VideoCapture1.OnVideoFrameBuffer += VideoCapture1_OnVideoFrameBuffer;
VideoCapture1.OnVideoFrameBufferOriginal += VideoCapture1_OnVideoFrameBufferOriginal;
VideoCapture1.OnVideoFrameBufferRAW += VideoCapture1_OnVideoFrameBufferRAW;
```

and the corresponding event handlers are:

        private void VideoCapture1_OnVideoFrameBufferRAW(object sender, VideoFrameBufferEventArgs e)
        {
            byte[] ar = e.FrameArray;
        }

        private void VideoCapture1_OnVideoFrameBufferOriginal(object sender, VideoFrameBufferEventArgs e)
        {
            byte[] ar = e.FrameArray;
        }

        private void VideoCapture1_OnVideoFrameBuffer(object sender, VideoFrameBufferEventArgs e)
        {
            byte[] ar = e.FrameArray;
        }

Expected behaviour:

- When I click the start button and see the video stream, the events should be triggered and e.FrameArray should return a byte array of the current frame.

Actual behaviour:

- `OnVideoFrameBufferRAW` is not triggered.
- The other 2 events are triggered, but both give me `null` from e.FrameArray.

I am kindly asking for help as getting the byte array straight is very useful.

Also, if there is anything that I am doing wrong, please let me know :)

**Comment by visioforge** [comment]
Hi

e.FrameArray is an optional field that usually empty. Frame located at e.Frame.Data (IntPtr) as an unmanaged memory array.

OnVideoFrameBuffer is an event that always available. Two other events are optional for specific situations.
