### ISSUE TITLE
SDK V15.3.4 dependency to WinForms 6.0.2.0 cannot be resolved on Windows 10

### ISSUE THREAD

**Issue by Dany-HBK** [visioforge/.Net-SDK-s-samples#6]
Hi,
after pulling the latest changes to the samples (SDK version 15.3.4) I get the compiler error
`1>CSC : error CS1705: Assembly 'VisioForge.Core.UI.WinForms' with identity 'VisioForge.Core.UI.WinForms, Version=15.3.4.0, Culture=neutral, PublicKeyToken=null' uses 'System.Windows.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' which has a higher version than referenced assembly 'System.Windows.Forms' with identity 'System.Windows.Forms, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'`
`1>Done building project "Main Demo VC (NuGet) net6.csproj" -- FAILED.`
`Build has been canceled.`

I'm using VS2022 Pro on Windows 10 21H2 (Build 19044.1526).
Kind regards,
Dany

**Comment by visioforge** [comment]
Problem resolved.
