### ISSUE TITLE
VisioForge.DotNet.MediaPlayer.TRIAL 15.1.12

### ISSUE THREAD

**Issue by idgregory** [visioforge/.Net-SDK-s-samples#8]
My company was looking to buy the visioforge framework and ran into a problem trying to play a MP4 file.  I keep getting a "Value cannot be null.  Parameter name: path1" error on the "OnError" event after calling the VisioForge.Core.MediaPlayer.MediaPlayerCore.PlayAsync() method.  Also, the variable _mediaCore is a type of VisioForge.Core.MediaPlayer.MediaPlayerCore.

`        private async Task SetVideoStream()
        {
            _MemoryStream?.Close();
            _memorySource = File.ReadAllBytes(oldFilename);
            _MemoryStream = new MemoryStream(_memorySource);
            _stream = new ManagedIStream(_MemoryStream);
            _mediaCore.Source_MemoryStream = new MemoryStreamSource(_stream, true, true, _MemoryStream.Length);
            _mediaCore.Audio_OutputDevice = "Default DirectSound Device";
            _mediaCore.Video_Renderer_SetAuto();
            _mediaCore.Debug_Mode = true;
            _mediaCore.Audio_PlayAudio = false;
            _mediaCore.Source_Mode = MediaPlayerSourceMode.Memory_DS;
            _mediaCore.Play_PauseAtFirstFrame = true;
            await _mediaCore.PlayAsync();

        }`

**Comment by visioforge** [comment]
Hi

Please check the following demo - https://github.com/visioforge/.Net-SDK-s-samples/tree/master/Media%20Player%20SDK/WinForms/CSharp/Memory%20Stream  

You can clone repo and use the latest SDK version.

**Comment by idgregory** [comment]
I think I had the wrong packages installed.  For testing purposes, would I be able to use the SDK if I published the application without a license?

**Comment by visioforge** [comment]
You can test the SDK without a license, within 30 days and with a "UNREGISTERED" logo.
